# Generated by Django 5.1.4 on 2025-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
